SELECT
    CAST(a.SK_ID_CURR AS BIGINT) AS SK_ID_CURR,
    CAST(a.TARGET AS TINYINT) AS TARGET,
    CAST(s.SPLIT AS VARCHAR) AS SPLIT,
    a.* EXCLUDE (SK_ID_CURR, TARGET, DAYS_EMPLOYED),
    CASE
        WHEN a.DAYS_EMPLOYED = 365243 THEN NULL
        ELSE CAST(a.DAYS_EMPLOYED AS DOUBLE)
    END AS DAYS_EMPLOYED,
    CAST(a.DAYS_EMPLOYED = 365243 AS TINYINT) AS DAYS_EMPLOYED_SENTINEL,
    CAST(a.FLAG_OWN_CAR = 'N' AND a.OWN_CAR_AGE IS NULL AS TINYINT)
        AS OWN_CAR_AGE_NOT_APPLICABLE,
    CAST(a.FLAG_OWN_CAR = 'Y' AND a.OWN_CAR_AGE IS NULL AS TINYINT)
        AS OWN_CAR_AGE_MISSING,
    CASE
        WHEN a.AMT_INCOME_TOTAL > 0
        THEN CAST(a.AMT_CREDIT AS DOUBLE) / a.AMT_INCOME_TOTAL
    END AS APP_CREDIT_INCOME_RATIO,
    CASE
        WHEN a.AMT_INCOME_TOTAL > 0
        THEN CAST(a.AMT_ANNUITY AS DOUBLE) / a.AMT_INCOME_TOTAL
    END AS APP_ANNUITY_INCOME_RATIO,
    CASE
        WHEN a.AMT_ANNUITY > 0
        THEN CAST(a.AMT_CREDIT AS DOUBLE) / a.AMT_ANNUITY
    END AS APP_CREDIT_ANNUITY_RATIO,
    CASE
        WHEN a.AMT_CREDIT > 0
        THEN CAST(a.AMT_GOODS_PRICE AS DOUBLE) / a.AMT_CREDIT
    END AS APP_CREDIT_GOODS_RATIO,
    CASE
        WHEN a.CNT_FAM_MEMBERS > 0
        THEN CAST(a.AMT_INCOME_TOTAL AS DOUBLE) / a.CNT_FAM_MEMBERS
    END AS APP_INCOME_PER_FAMILY_MEMBER,
    CASE
        WHEN a.DAYS_BIRTH < 0
        THEN -CAST(a.DAYS_BIRTH AS DOUBLE) / 365.25
    END AS APP_AGE_YEARS,
    CASE
        WHEN a.DAYS_EMPLOYED < 0 AND a.DAYS_EMPLOYED <> 365243
        THEN -CAST(a.DAYS_EMPLOYED AS DOUBLE) / 365.25
    END AS APP_EMPLOYED_YEARS,
    CASE
        WHEN a.DAYS_EMPLOYED < 0
         AND a.DAYS_EMPLOYED <> 365243
         AND a.DAYS_BIRTH < 0
        THEN CAST(a.DAYS_EMPLOYED AS DOUBLE) / a.DAYS_BIRTH
    END AS APP_EMPLOYED_AGE_RATIO,
    CAST(
        (a.EXT_SOURCE_1 IS NOT NULL)::INTEGER
        + (a.EXT_SOURCE_2 IS NOT NULL)::INTEGER
        + (a.EXT_SOURCE_3 IS NOT NULL)::INTEGER
        AS TINYINT
    ) AS APP_EXT_SOURCE_OBSERVED_COUNT,
    CASE
        WHEN (a.EXT_SOURCE_1 IS NOT NULL)::INTEGER
           + (a.EXT_SOURCE_2 IS NOT NULL)::INTEGER
           + (a.EXT_SOURCE_3 IS NOT NULL)::INTEGER > 0
        THEN (
            COALESCE(CAST(a.EXT_SOURCE_1 AS DOUBLE), 0.0)
            + COALESCE(CAST(a.EXT_SOURCE_2 AS DOUBLE), 0.0)
            + COALESCE(CAST(a.EXT_SOURCE_3 AS DOUBLE), 0.0)
        ) / (
            (a.EXT_SOURCE_1 IS NOT NULL)::INTEGER
            + (a.EXT_SOURCE_2 IS NOT NULL)::INTEGER
            + (a.EXT_SOURCE_3 IS NOT NULL)::INTEGER
        )
    END AS APP_EXT_SOURCE_MEAN
FROM application_source AS a
INNER JOIN split_source AS s
    ON a.SK_ID_CURR = s.SK_ID_CURR
   AND a.TARGET = s.TARGET
ORDER BY a.SK_ID_CURR
