WITH scoped AS (
    SELECT b.*
    FROM bureau_source AS b
    INNER JOIN application_ids AS a USING (SK_ID_CURR)
    WHERE b.DAYS_CREDIT_UPDATE <= 0
)
SELECT
    CAST(SK_ID_CURR AS BIGINT) AS SK_ID_CURR,
    CAST(COUNT(*) AS BIGINT) AS BUREAU_RECORD_COUNT,
    CAST(COUNT(DISTINCT SK_ID_BUREAU) AS BIGINT) AS BUREAU_LOAN_COUNT,
    CAST(COUNT(*) FILTER (WHERE CREDIT_ACTIVE = 'Active') AS BIGINT)
        AS BUREAU_ACTIVE_COUNT,
    CAST(COUNT(*) FILTER (WHERE CREDIT_ACTIVE = 'Closed') AS BIGINT)
        AS BUREAU_CLOSED_COUNT,
    CAST(COUNT(*) FILTER (WHERE CREDIT_ACTIVE = 'Sold') AS BIGINT)
        AS BUREAU_SOLD_COUNT,
    CAST(COUNT(*) FILTER (WHERE CREDIT_ACTIVE = 'Bad debt') AS BIGINT)
        AS BUREAU_BAD_DEBT_COUNT,
    CAST(COUNT(DISTINCT CREDIT_TYPE) AS BIGINT) AS BUREAU_CREDIT_TYPE_COUNT,
    CAST(COUNT(*) FILTER (WHERE CREDIT_CURRENCY <> 'currency 1') AS BIGINT)
        AS BUREAU_NON_PRIMARY_CURRENCY_COUNT,
    CAST(COUNT(*) FILTER (
        WHERE CREDIT_DAY_OVERDUE > 0 OR AMT_CREDIT_SUM_OVERDUE > 0
    ) AS BIGINT) AS BUREAU_OVERDUE_LOAN_COUNT,
    COUNT(*) FILTER (WHERE CREDIT_ACTIVE = 'Active')::DOUBLE
        / NULLIF(COUNT(*), 0) AS BUREAU_ACTIVE_RATIO,
    COUNT(*) FILTER (
        WHERE CREDIT_DAY_OVERDUE > 0 OR AMT_CREDIT_SUM_OVERDUE > 0
    )::DOUBLE / NULLIF(COUNT(*), 0) AS BUREAU_OVERDUE_LOAN_RATIO,
    AVG(CAST(DAYS_CREDIT AS DOUBLE)) AS BUREAU_DAYS_CREDIT_MEAN,
    MIN(CAST(DAYS_CREDIT AS DOUBLE)) AS BUREAU_DAYS_CREDIT_MIN,
    MAX(CAST(DAYS_CREDIT AS DOUBLE)) AS BUREAU_DAYS_CREDIT_MAX,
    -MAX(CAST(DAYS_CREDIT AS DOUBLE)) AS BUREAU_DAYS_SINCE_RECENT_CREDIT,
    AVG(CAST(CREDIT_DAY_OVERDUE AS DOUBLE)) AS BUREAU_DAYS_OVERDUE_MEAN,
    MAX(CAST(CREDIT_DAY_OVERDUE AS DOUBLE)) AS BUREAU_DAYS_OVERDUE_MAX,
    SUM(CAST(CNT_CREDIT_PROLONG AS DOUBLE)) AS BUREAU_PROLONG_COUNT_SUM,
    CAST(COUNT(AMT_CREDIT_SUM) FILTER (WHERE CREDIT_CURRENCY = 'currency 1') AS BIGINT)
        AS BUREAU_CREDIT_AMOUNT_OBSERVED_COUNT,
    SUM(CAST(AMT_CREDIT_SUM AS DOUBLE)) FILTER (WHERE CREDIT_CURRENCY = 'currency 1')
        AS BUREAU_CREDIT_AMOUNT_SUM,
    AVG(CAST(AMT_CREDIT_SUM AS DOUBLE)) FILTER (WHERE CREDIT_CURRENCY = 'currency 1')
        AS BUREAU_CREDIT_AMOUNT_MEAN,
    MAX(CAST(AMT_CREDIT_SUM AS DOUBLE)) FILTER (WHERE CREDIT_CURRENCY = 'currency 1')
        AS BUREAU_CREDIT_AMOUNT_MAX,
    CAST(COUNT(AMT_CREDIT_SUM_DEBT) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BIGINT) AS BUREAU_DEBT_OBSERVED_COUNT,
    SUM(CAST(AMT_CREDIT_SUM_DEBT AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BUREAU_DEBT_SUM,
    AVG(CAST(AMT_CREDIT_SUM_DEBT AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BUREAU_DEBT_MEAN,
    MAX(CAST(AMT_CREDIT_SUM_DEBT AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BUREAU_DEBT_MAX,
    SUM(CAST(AMT_CREDIT_SUM_OVERDUE AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BUREAU_OVERDUE_AMOUNT_SUM,
    MAX(CAST(AMT_CREDIT_SUM_OVERDUE AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BUREAU_OVERDUE_AMOUNT_MAX,
    CAST(COUNT(AMT_CREDIT_MAX_OVERDUE) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BIGINT)
        AS BUREAU_MAX_OVERDUE_OBSERVED_COUNT,
    MAX(CAST(AMT_CREDIT_MAX_OVERDUE AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
    ) AS BUREAU_MAX_OVERDUE_AMOUNT,
    SUM(CAST(AMT_CREDIT_SUM AS DOUBLE)) FILTER (
        WHERE CREDIT_ACTIVE = 'Active' AND CREDIT_CURRENCY = 'currency 1'
    )
        AS BUREAU_ACTIVE_CREDIT_SUM,
    SUM(CAST(AMT_CREDIT_SUM_DEBT AS DOUBLE)) FILTER (
        WHERE CREDIT_ACTIVE = 'Active' AND CREDIT_CURRENCY = 'currency 1'
    )
        AS BUREAU_ACTIVE_DEBT_SUM,
    SUM(CAST(AMT_CREDIT_SUM_DEBT AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
          AND AMT_CREDIT_SUM_DEBT IS NOT NULL
          AND AMT_CREDIT_SUM IS NOT NULL
    ) / NULLIF(SUM(CAST(AMT_CREDIT_SUM AS DOUBLE)) FILTER (
        WHERE CREDIT_CURRENCY = 'currency 1'
          AND AMT_CREDIT_SUM_DEBT IS NOT NULL
          AND AMT_CREDIT_SUM IS NOT NULL
    ), 0)
        AS BUREAU_DEBT_CREDIT_RATIO,
    CAST(COUNT(AMT_ANNUITY) FILTER (WHERE CREDIT_CURRENCY = 'currency 1') AS BIGINT)
        AS BUREAU_ANNUITY_OBSERVED_COUNT,
    SUM(CAST(AMT_ANNUITY AS DOUBLE)) FILTER (WHERE CREDIT_CURRENCY = 'currency 1')
        AS BUREAU_ANNUITY_SUM,
    AVG(CAST(AMT_ANNUITY AS DOUBLE)) FILTER (WHERE CREDIT_CURRENCY = 'currency 1')
        AS BUREAU_ANNUITY_MEAN
FROM scoped
GROUP BY SK_ID_CURR
