SELECT
    v1.*,
    CAST(b.SK_ID_CURR IS NOT NULL AS TINYINT) AS BUREAU_HAS_HISTORY,
    COALESCE(b.BUREAU_RECORD_COUNT, 0) AS BUREAU_RECORD_COUNT,
    COALESCE(b.BUREAU_LOAN_COUNT, 0) AS BUREAU_LOAN_COUNT,
    COALESCE(b.BUREAU_ACTIVE_COUNT, 0) AS BUREAU_ACTIVE_COUNT,
    COALESCE(b.BUREAU_CLOSED_COUNT, 0) AS BUREAU_CLOSED_COUNT,
    COALESCE(b.BUREAU_SOLD_COUNT, 0) AS BUREAU_SOLD_COUNT,
    COALESCE(b.BUREAU_BAD_DEBT_COUNT, 0) AS BUREAU_BAD_DEBT_COUNT,
    COALESCE(b.BUREAU_CREDIT_TYPE_COUNT, 0) AS BUREAU_CREDIT_TYPE_COUNT,
    COALESCE(b.BUREAU_NON_PRIMARY_CURRENCY_COUNT, 0)
        AS BUREAU_NON_PRIMARY_CURRENCY_COUNT,
    COALESCE(b.BUREAU_OVERDUE_LOAN_COUNT, 0) AS BUREAU_OVERDUE_LOAN_COUNT,
    b.BUREAU_ACTIVE_RATIO,
    b.BUREAU_OVERDUE_LOAN_RATIO,
    b.BUREAU_DAYS_CREDIT_MEAN,
    b.BUREAU_DAYS_CREDIT_MIN,
    b.BUREAU_DAYS_CREDIT_MAX,
    b.BUREAU_DAYS_SINCE_RECENT_CREDIT,
    b.BUREAU_DAYS_OVERDUE_MEAN,
    b.BUREAU_DAYS_OVERDUE_MAX,
    COALESCE(b.BUREAU_PROLONG_COUNT_SUM, 0.0) AS BUREAU_PROLONG_COUNT_SUM,
    COALESCE(b.BUREAU_CREDIT_AMOUNT_OBSERVED_COUNT, 0)
        AS BUREAU_CREDIT_AMOUNT_OBSERVED_COUNT,
    b.BUREAU_CREDIT_AMOUNT_SUM,
    b.BUREAU_CREDIT_AMOUNT_MEAN,
    b.BUREAU_CREDIT_AMOUNT_MAX,
    COALESCE(b.BUREAU_DEBT_OBSERVED_COUNT, 0) AS BUREAU_DEBT_OBSERVED_COUNT,
    b.BUREAU_DEBT_SUM,
    b.BUREAU_DEBT_MEAN,
    b.BUREAU_DEBT_MAX,
    b.BUREAU_OVERDUE_AMOUNT_SUM,
    b.BUREAU_OVERDUE_AMOUNT_MAX,
    COALESCE(b.BUREAU_MAX_OVERDUE_OBSERVED_COUNT, 0)
        AS BUREAU_MAX_OVERDUE_OBSERVED_COUNT,
    b.BUREAU_MAX_OVERDUE_AMOUNT,
    b.BUREAU_ACTIVE_CREDIT_SUM,
    b.BUREAU_ACTIVE_DEBT_SUM,
    b.BUREAU_DEBT_CREDIT_RATIO,
    COALESCE(b.BUREAU_ANNUITY_OBSERVED_COUNT, 0)
        AS BUREAU_ANNUITY_OBSERVED_COUNT,
    b.BUREAU_ANNUITY_SUM,
    b.BUREAU_ANNUITY_MEAN
FROM v1_source AS v1
LEFT JOIN bureau_features AS b USING (SK_ID_CURR)
ORDER BY v1.SK_ID_CURR
