WITH scoped AS (
    SELECT i.*
    FROM installments_source AS i
    INNER JOIN application_ids AS a USING (SK_ID_CURR)
), installment_level AS (
    SELECT
        SK_ID_CURR,
        SK_ID_PREV,
        NUM_INSTALMENT_VERSION,
        NUM_INSTALMENT_NUMBER,
        MIN(CAST(DAYS_INSTALMENT AS DOUBLE)) AS DAYS_DUE,
        MAX(CAST(DAYS_ENTRY_PAYMENT AS DOUBLE)) AS RAW_DAYS_PAID_LAST,
        MAX(CAST(AMT_INSTALMENT AS DECIMAL(38, 6))) AS SCHEDULED_AMOUNT,
        SUM(CAST(AMT_PAYMENT AS DECIMAL(38, 6))) AS RAW_PAID_AMOUNT,
        CAST(COUNT(*) AS BIGINT) AS PAYMENT_EVENT_COUNT,
        CAST(COUNT(*) FILTER (
            WHERE DAYS_ENTRY_PAYMENT IS NULL OR AMT_PAYMENT IS NULL
        ) AS BIGINT) AS MISSING_PAYMENT_EVENT_COUNT
    FROM scoped
    GROUP BY
        SK_ID_CURR,
        SK_ID_PREV,
        NUM_INSTALMENT_VERSION,
        NUM_INSTALMENT_NUMBER
), derived AS (
    SELECT
        *,
        CASE
            WHEN MISSING_PAYMENT_EVENT_COUNT = 0 THEN RAW_DAYS_PAID_LAST
        END AS DAYS_PAID_LAST,
        CASE
            WHEN MISSING_PAYMENT_EVENT_COUNT = 0 THEN RAW_PAID_AMOUNT
        END AS PAID_AMOUNT,
        CASE
            WHEN MISSING_PAYMENT_EVENT_COUNT = 0 AND RAW_DAYS_PAID_LAST IS NOT NULL
            THEN GREATEST(RAW_DAYS_PAID_LAST - DAYS_DUE, 0.0)
        END AS DAYS_LATE,
        CASE
            WHEN MISSING_PAYMENT_EVENT_COUNT = 0 AND SCHEDULED_AMOUNT IS NOT NULL
            THEN GREATEST(SCHEDULED_AMOUNT - RAW_PAID_AMOUNT, 0.0)
        END AS PAYMENT_GAP,
        CASE
            WHEN MISSING_PAYMENT_EVENT_COUNT = 0 AND SCHEDULED_AMOUNT > 0
            THEN RAW_PAID_AMOUNT / SCHEDULED_AMOUNT
        END AS PAYMENT_RATIO,
        CASE
            WHEN MISSING_PAYMENT_EVENT_COUNT = 0 AND SCHEDULED_AMOUNT > 0
            THEN CAST(RAW_PAID_AMOUNT + 0.01 < SCHEDULED_AMOUNT AS TINYINT)
        END AS IS_UNDERPAID
    FROM installment_level
)
SELECT
    CAST(SK_ID_CURR AS BIGINT) AS SK_ID_CURR,
    CAST(COUNT(*) AS BIGINT) AS INST_SCHEDULE_COUNT,
    CAST(COUNT(DISTINCT SK_ID_PREV) AS BIGINT) AS INST_PREV_LOAN_COUNT,
    CAST(SUM(PAYMENT_EVENT_COUNT) AS BIGINT) AS INST_PAYMENT_EVENT_COUNT,
    CAST(COUNT(DAYS_PAID_LAST) AS BIGINT)
        AS INST_PAYMENT_DATE_OBSERVED_SCHEDULE_COUNT,
    CAST(COUNT(PAID_AMOUNT) AS BIGINT)
        AS INST_PAYMENT_AMOUNT_OBSERVED_SCHEDULE_COUNT,
    CAST(COUNT(*) FILTER (WHERE MISSING_PAYMENT_EVENT_COUNT > 0) AS BIGINT)
        AS INST_MISSING_PAYMENT_SCHEDULE_COUNT,
    COUNT(*) FILTER (WHERE MISSING_PAYMENT_EVENT_COUNT > 0)::DOUBLE
        / NULLIF(COUNT(*), 0)
        AS INST_MISSING_PAYMENT_RATIO,
    CAST(COUNT(*) FILTER (WHERE DAYS_LATE > 0) AS BIGINT)
        AS INST_LATE_SCHEDULE_COUNT,
    COUNT(*) FILTER (WHERE DAYS_LATE > 0)::DOUBLE
        / NULLIF(COUNT(DAYS_LATE), 0) AS INST_LATE_RATIO,
    AVG(DAYS_LATE) AS INST_DAYS_LATE_MEAN,
    MAX(DAYS_LATE) AS INST_DAYS_LATE_MAX,
    SUM(DAYS_LATE) AS INST_DAYS_LATE_SUM,
    CAST(COUNT(*) FILTER (WHERE IS_UNDERPAID = 1) AS BIGINT)
        AS INST_UNDERPAID_SCHEDULE_COUNT,
    COUNT(*) FILTER (WHERE IS_UNDERPAID = 1)::DOUBLE
        / NULLIF(COUNT(IS_UNDERPAID), 0) AS INST_UNDERPAID_RATIO,
    CAST(SUM(SCHEDULED_AMOUNT) AS DOUBLE) AS INST_SCHEDULED_AMOUNT_SUM,
    CAST(SUM(PAID_AMOUNT) AS DOUBLE) AS INST_PAID_AMOUNT_SUM,
    CAST(SUM(PAYMENT_GAP) AS DOUBLE) AS INST_PAYMENT_GAP_SUM,
    CAST(MAX(PAYMENT_GAP) AS DOUBLE) AS INST_PAYMENT_GAP_MAX,
    SUM(PAID_AMOUNT)::DOUBLE / NULLIF(
        SUM(SCHEDULED_AMOUNT) FILTER (WHERE PAID_AMOUNT IS NOT NULL), 0
    ) AS INST_PAYMENT_RATIO,
    -MAX(DAYS_DUE) AS INST_DAYS_SINCE_RECENT_DUE,
    -MIN(DAYS_DUE) AS INST_OLDEST_DUE_AGE_DAYS,
    MAX(DAYS_DUE) - MIN(DAYS_DUE) AS INST_HISTORY_SPAN_DAYS,
    CAST(COUNT(*) FILTER (WHERE DAYS_DUE >= -365) AS BIGINT)
        AS INST_LAST_365_SCHEDULE_COUNT,
    CAST(COUNT(*) FILTER (WHERE DAYS_DUE >= -365 AND DAYS_LATE > 0) AS BIGINT)
        AS INST_LAST_365_LATE_COUNT,
    COUNT(*) FILTER (WHERE DAYS_DUE >= -365 AND DAYS_LATE > 0)::DOUBLE
        / NULLIF(COUNT(*) FILTER (
            WHERE DAYS_DUE >= -365 AND DAYS_PAID_LAST IS NOT NULL
        ), 0) AS INST_LAST_365_LATE_RATIO,
    CAST(COUNT(*) FILTER (WHERE DAYS_DUE >= -730) AS BIGINT)
        AS INST_LAST_730_SCHEDULE_COUNT,
    CAST(COUNT(*) FILTER (WHERE DAYS_DUE >= -730 AND DAYS_LATE > 0) AS BIGINT)
        AS INST_LAST_730_LATE_COUNT,
    COUNT(*) FILTER (WHERE DAYS_DUE >= -730 AND DAYS_LATE > 0)::DOUBLE
        / NULLIF(COUNT(*) FILTER (
            WHERE DAYS_DUE >= -730 AND DAYS_PAID_LAST IS NOT NULL
        ), 0) AS INST_LAST_730_LATE_RATIO
FROM derived
GROUP BY SK_ID_CURR
