SELECT
    v2.*,
    CAST(i.SK_ID_CURR IS NOT NULL AS TINYINT) AS INST_HAS_HISTORY,
    COALESCE(i.INST_SCHEDULE_COUNT, 0) AS INST_SCHEDULE_COUNT,
    COALESCE(i.INST_PREV_LOAN_COUNT, 0) AS INST_PREV_LOAN_COUNT,
    COALESCE(i.INST_PAYMENT_EVENT_COUNT, 0) AS INST_PAYMENT_EVENT_COUNT,
    COALESCE(i.INST_PAYMENT_DATE_OBSERVED_SCHEDULE_COUNT, 0)
        AS INST_PAYMENT_DATE_OBSERVED_SCHEDULE_COUNT,
    COALESCE(i.INST_PAYMENT_AMOUNT_OBSERVED_SCHEDULE_COUNT, 0)
        AS INST_PAYMENT_AMOUNT_OBSERVED_SCHEDULE_COUNT,
    COALESCE(i.INST_MISSING_PAYMENT_SCHEDULE_COUNT, 0)
        AS INST_MISSING_PAYMENT_SCHEDULE_COUNT,
    i.INST_MISSING_PAYMENT_RATIO,
    COALESCE(i.INST_LATE_SCHEDULE_COUNT, 0) AS INST_LATE_SCHEDULE_COUNT,
    i.INST_LATE_RATIO,
    i.INST_DAYS_LATE_MEAN,
    i.INST_DAYS_LATE_MAX,
    i.INST_DAYS_LATE_SUM,
    COALESCE(i.INST_UNDERPAID_SCHEDULE_COUNT, 0)
        AS INST_UNDERPAID_SCHEDULE_COUNT,
    i.INST_UNDERPAID_RATIO,
    i.INST_SCHEDULED_AMOUNT_SUM,
    i.INST_PAID_AMOUNT_SUM,
    i.INST_PAYMENT_GAP_SUM,
    i.INST_PAYMENT_GAP_MAX,
    i.INST_PAYMENT_RATIO,
    i.INST_DAYS_SINCE_RECENT_DUE,
    i.INST_OLDEST_DUE_AGE_DAYS,
    i.INST_HISTORY_SPAN_DAYS,
    COALESCE(i.INST_LAST_365_SCHEDULE_COUNT, 0)
        AS INST_LAST_365_SCHEDULE_COUNT,
    COALESCE(i.INST_LAST_365_LATE_COUNT, 0) AS INST_LAST_365_LATE_COUNT,
    i.INST_LAST_365_LATE_RATIO,
    COALESCE(i.INST_LAST_730_SCHEDULE_COUNT, 0)
        AS INST_LAST_730_SCHEDULE_COUNT,
    COALESCE(i.INST_LAST_730_LATE_COUNT, 0) AS INST_LAST_730_LATE_COUNT,
    i.INST_LAST_730_LATE_RATIO
FROM v2_source AS v2
LEFT JOIN installment_features AS i USING (SK_ID_CURR)
ORDER BY v2.SK_ID_CURR
